# Generated by Django 2.2 on 2020-08-20 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=40)),
                ('subject_teacher', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='logincred',
            name='name',
            field=models.CharField(default='abcd', max_length=40),
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=10)),
                ('marks', models.CharField(max_length=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.LoginCred')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(max_length=40)),
                ('percentage', models.CharField(max_length=10)),
                ('present_days', models.CharField(max_length=10)),
                ('total_days', models.CharField(max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.LoginCred')),
            ],
        ),
    ]
