# Generated by Django 2.2 on 2020-08-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200820_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincred',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
