# Generated by Django 2.2 on 2020-08-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200820_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('course', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=5)),
            ],
        ),
    ]
